server:
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:54320/postgres
    username: user
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
